### DISCUSSION TITLE
Always have "Signature verification failed" while downloading from GCP

### DISCUSSION THREAD

**Discussion by hacktisch** [hiero-ledger/hiero-mirror-node#2418] [Help] [answered]
My synchronization seems to be stuck, I can't figure out why. 
I am using the following application.yml, and the logs are below (that keep repeating forever, always stuck on '2019-10-11T16_39_31.290027001Z_')

application.yml:
````
hedera:
  mirror:
    importer:
      downloader:
        accessKey: GOOG4...........................................
        cloudProvider: 'GCP'
        gcpProjectId: .......................
        secretKey: cyY.............................................................
      network: 'MAINNET'
````

output:
````
importer_1  | 2021-08-17T08:26:59.764-0600 WARN scheduling-2 c.h.m.i.d.r.RecordFileDownloader Signature verification failed but still have files in the batch, try to process the next group: Signature verification failed for file 2019-10-11T16_42_25.347093Z.rcd_sig: {DOWNLOADED=[0.0.3, 0.0.4, 0.0.5, 0.0.6], NOT_FOUND=[]} 
importer_1  | 2021-08-17T08:26:59.764-0600 WARN scheduling-2 c.h.m.i.d.r.RecordFileDownloader Signature verification failed but still have files in the batch, try to process the next group: Signature verification failed for file 2019-10-11T16_42_30.028491Z.rcd_sig: {DOWNLOADED=[0.0.3, 0.0.4, 0.0.5, 0.0.6], NOT_FOUND=[]} 
importer_1  | 2021-08-17T08:26:59.765-0600 WARN scheduling-2 c.h.m.i.d.r.RecordFileDownloader Signature verification failed but still have files in the batch, try to process the next group: Signature verification failed for file 2019-10-11T16_42_35.820808Z.rcd_sig: {DOWNLOADED=[0.0.3, 0.0.4, 0.0.5, 0.0.6], NOT_FOUND=[]} 
importer_1  | 2021-08-17T08:26:59.766-0600 WARN scheduling-2 c.h.m.i.d.r.RecordFileDownloader Signature verification failed but still have files in the batch, try to process the next group: Signature verification failed for file 2019-10-11T16_42_40.111398002Z.rcd_sig: {DOWNLOADED=[0.0.3, 0.0.4, 0.0.5, 0.0.6], NOT_FOUND=[]} 
importer_1  | 2021-08-17T08:26:59.767-0600 WARN scheduling-2 c.h.m.i.d.r.RecordFileDownloader Signature verification failed but still have files in the batch, try to process the next group: Signature verification failed for file 2019-10-11T16_42_45.207705Z.rcd_sig: {DOWNLOADED=[0.0.3, 0.0.4, 0.0.5, 0.0.6], NOT_FOUND=[]} 
importer_1  | 2021-08-17T08:26:59.767-0600 WARN scheduling-2 c.h.m.i.d.r.RecordFileDownloader Signature verification failed for file 2019-10-11T16_42_50.697476Z.rcd_sig: {DOWNLOADED=[0.0.3, 0.0.4, 0.0.5, 0.0.6], NOT_FOUND=[]} 
importer_1  | 2021-08-17T08:27:00.268-0600 INFO scheduling-2 c.h.m.i.d.r.RecordFileDownloader Downloading signature files created after file: 2019-10-11T16_39_31.290027001Z_ 
importer_1  | 2021-08-17T08:27:00.936-0600 INFO pool-9-thread-10 c.h.m.i.d.r.RecordFileDownloader Downloaded 40 signatures for node 0.0.3 in 668.3 ms 
````
