### ISSUE TITLE
Unable to use path prefix to download block file

### ISSUE THREAD

**Issue by xin-hedera** [hiero-ledger/hiero-mirror-node#10612]
### Description

When importer is configured with a cloud bucket `pathPrefix` and `BlockStreamPoller` is enabled to download block stream files, no files seem to get downloaded.

### Steps to reproduce

run importer with

```yaml
hedera:
  mirror:
    importer:
      downloader:
        block:
          enabled: true
        bucketName: test-bucket
        pathType: NODE_ID
        pathPrefix: testPrefix
```

### Version

v0.126.0-SNAPSHOT

### Operating system

None
