### ISSUE TITLE
Support AWS IAM role bind for AWS S3 bucket access

### ISSUE THREAD

**Issue by nooperpudd** [hiero-ledger/hiero-mirror-node#10805]
### Problem

```yaml
hedera:
  mirror:
    importer:
      network: MAINNET # Select one of PREVIEWNET/TESTNET/MAINNET and populate below config
      downloader:
        cloudProvider: "S3"
        secretKey:
        accessKey:
```
to configure the secretKey and accessKey in configuration file would be a security risk. please support to AWS IAM role.  

### Solution

AWS IAM role to bind the AWS policy without the AWS secret key.
